# Site settings
title: *yueguoguo
email: yueguoguo1024@gmail.com 
description: > Explosions of random thoughts
# baseurl: the subpath of your site, e.g. /blog/
url: yueguoguo.github.io
twitter_username: yueguoguo 
github_username: yueguoguo 

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


